"""init priconne orm

迁移 ID: e828532300c4
父迁移: 
创建时间: 2026-03-15 01:54:04.201509

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e828532300c4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priconne_apply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('boss', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priconne_apply')),
    info={'bind_key': 'priconne'}
    )
    with op.batch_alter_table('priconne_apply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priconne_apply_group_id'), ['group_id'], unique=False)

    op.create_table('priconne_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('pcrid', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('lap', sa.Integer(), nullable=False),
    sa.Column('boss', sa.String(length=16), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('flag', sa.Float(), nullable=False),
    sa.Column('battle_log_id', sa.Integer(), nullable=False),
    sa.Column('remain_time', sa.Integer(), nullable=False),
    sa.Column('battle_time', sa.Integer(), nullable=False),
    sa.Column('unit1', sa.Integer(), nullable=False),
    sa.Column('unit2', sa.Integer(), nullable=False),
    sa.Column('unit3', sa.Integer(), nullable=False),
    sa.Column('unit4', sa.Integer(), nullable=False),
    sa.Column('unit5', sa.Integer(), nullable=False),
    sa.Column('unit1_level', sa.Integer(), nullable=False),
    sa.Column('unit2_level', sa.Integer(), nullable=False),
    sa.Column('unit3_level', sa.Integer(), nullable=False),
    sa.Column('unit4_level', sa.Integer(), nullable=False),
    sa.Column('unit5_level', sa.Integer(), nullable=False),
    sa.Column('unit1_damage', sa.Integer(), nullable=False),
    sa.Column('unit2_damage', sa.Integer(), nullable=False),
    sa.Column('unit3_damage', sa.Integer(), nullable=False),
    sa.Column('unit4_damage', sa.Integer(), nullable=False),
    sa.Column('unit5_damage', sa.Integer(), nullable=False),
    sa.Column('unit1_rarity', sa.Integer(), nullable=False),
    sa.Column('unit2_rarity', sa.Integer(), nullable=False),
    sa.Column('unit3_rarity', sa.Integer(), nullable=False),
    sa.Column('unit4_rarity', sa.Integer(), nullable=False),
    sa.Column('unit5_rarity', sa.Integer(), nullable=False),
    sa.Column('unit1_rank', sa.Integer(), nullable=False),
    sa.Column('unit2_rank', sa.Integer(), nullable=False),
    sa.Column('unit3_rank', sa.Integer(), nullable=False),
    sa.Column('unit4_rank', sa.Integer(), nullable=False),
    sa.Column('unit5_rank', sa.Integer(), nullable=False),
    sa.Column('unit1_unique_equip', sa.Integer(), nullable=False),
    sa.Column('unit2_unique_equip', sa.Integer(), nullable=False),
    sa.Column('unit3_unique_equip', sa.Integer(), nullable=False),
    sa.Column('unit4_unique_equip', sa.Integer(), nullable=False),
    sa.Column('unit5_unique_equip', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priconne_record')),
    info={'bind_key': 'priconne'}
    )
    with op.batch_alter_table('priconne_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priconne_record_group_id'), ['group_id'], unique=False)

    op.create_table('priconne_sl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('last_sl', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priconne_sl')),
    info={'bind_key': 'priconne'}
    )
    with op.batch_alter_table('priconne_sl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priconne_sl_group_id'), ['group_id'], unique=False)

    op.create_table('priconne_subscribe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('boss', sa.Integer(), nullable=False),
    sa.Column('lap', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priconne_subscribe')),
    info={'bind_key': 'priconne'}
    )
    with op.batch_alter_table('priconne_subscribe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priconne_subscribe_group_id'), ['group_id'], unique=False)

    op.create_table('priconne_tree',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('boss', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priconne_tree')),
    info={'bind_key': 'priconne'}
    )
    with op.batch_alter_table('priconne_tree', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priconne_tree_group_id'), ['group_id'], unique=False)

    op.create_table('priconne_winrecord',
    sa.Column('gid', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('gid', 'uid', name=op.f('pk_priconne_winrecord')),
    info={'bind_key': 'priconne'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priconne_winrecord')
    with op.batch_alter_table('priconne_tree', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priconne_tree_group_id'))

    op.drop_table('priconne_tree')
    with op.batch_alter_table('priconne_subscribe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priconne_subscribe_group_id'))

    op.drop_table('priconne_subscribe')
    with op.batch_alter_table('priconne_sl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priconne_sl_group_id'))

    op.drop_table('priconne_sl')
    with op.batch_alter_table('priconne_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priconne_record_group_id'))

    op.drop_table('priconne_record')
    with op.batch_alter_table('priconne_apply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priconne_apply_group_id'))

    op.drop_table('priconne_apply')
    # ### end Alembic commands ###
